language: node_js
addons:
  ssh_known_hosts: 3.120.249.73
cache:
  directories:
  - node_modules
  - $HOME/.npm
notifications:
  email: false
node_js: 10
before_install:
- npm install -g npm@6
install:
- npm install
deploy:
  provider: script
  script: ./scripts/publish.sh
  on:
    branch: development
