export const GET_ACCOUNT_DATA = 'GET_ACCOUNT_DATA'
export const UPDATE_ACCOUNT_DATA = 'UPDATE_ACCOUNT_DATA'
export const DISABLE_ACCOUNT_VISIBILITY = 'DISABLE_ACCOUNT_VISIBILITY'
export const ENABLE_ACCOUNT_VISIBILITY = 'ENABLE_ACCOUNT_VISIBILITY'
